### ISSUE TITLE
Is domain number 21, 18 or 20?

### ISSUE THREAD

**Issue by hdzhang-code** [xliuhw/NLU-Evaluation-Data#3]
Hi, 

In the original paper, https://arxiv.org/pdf/1903.05566.pdf, the domain number is declared to be 21.

However, after I collect all 'scenario' in NLU-Data-Home-Domain-Annotated-All.csv, the 'scenario ' number is 18:
{'cooking', 'lists', 'general', 'qa', 'calendar', 'social', 'iot', 'email', '        news', 'transport', 'play', 'recommendation', 'takeaway', 'music', 'audio', '        datetime', 'alarm', 'weather'}

I suppose some scenario may have several domains. For example, iot_cleaning and iot_hue_xxxx shall belong to different domain. Following this principle, I count the domain number in Table 5 in original paper. The result is 20.

![image](https://user-images.githubusercontent.com/59167334/99041670-4f5a4380-25c6-11eb-9924-68501ac755b6.png)

So what is the exact domain number, 21, 18 or 20? What are they?

Thanks!
Best Regards

**Comment by xliuhw** [comment]
Firstly, my apologies for late reply as I haven't checked the dataset in the github for a while.

Thanks for interested in the dataset and come up with the questions.

The '21 domains' in the paper was counted from the original dataset designed and collected (after the initial preprocessing). From the column of 'scenario' of paraphrases_and_intents_26k_normalised_all.csv you can see 
there are 23 scenarios. They are:

alarm, calendar, email, reminder, audio, podcasts, IOT, general, lists,transport, datetime
cooking, takeaway, contacts, news, music, radio, recommendation, weather, QA
social, audiobook, game

The initial preprocessing had merged some scenarios, 'reminder' and 'contacts' if I remember it correctly.
So 21 scenarios were left ( the '21' domains).

The latest annotated dataset contained 18 scenarios (which covers the 21 domains) :
alarm, audio, iot, calendar, play, general, datetime, takeaway, news, music, weather, qa, social, 
recommendation, cooking, email, transport, lists.

Please note that the 'domain' does not strictly correspond to the 'scenario' in the annotated dataset.
(though roughly you could consider a 'scenario' as a 'domain')
In the annotated dataset, we have re-organized the scenarios and intents for the better NLU clarifications.

From original dataset you can see there are scenarios like 'podcasts', 'radio', 'music' and 'game' etc,
they were merged/re-organized in the annotated dataset as 'play', 'music' etc.


By the way, your counts on 'Table 5' seems not correct, it should be 18.

Hope these answer your questions.
