### ISSUE TITLE
just fyi - I translated the asnwers to German

### ISSUE THREAD

**Issue by PhilipMay** [xliuhw/NLU-Evaluation-Data#9]
I translated the answers to German language and open sourced the dataset again. Many thanks for your work.

I just wanted to let you know.

https://github.com/t-systems-on-site-services-gmbh/NLU-Evaluation-Data-de-en

**Comment by xliuhw** [comment]
Great! Thanks for your translation work and having open-sourced it. And thanks for letting us know.
